### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by richstokes** [paulcwatts/ember-cognito#81]
Hi there, 

After following the install instructions I get the following after adding my Cognito settings to environment.js:

```- stack: /Users/x/Desktop/aws cognito/super-rentals/config/environment.js:27
    cognito: {
    ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

```> $ ember -v                                                                                                                                                        
ember-cli: 3.0.2
node: 9.10.1
os: darwin x64
```

**Comment by paulcwatts** [comment]
Hi @richstokes, this looks like it's a syntax error in your `config/environment.js` file. Can you paste more of that file? It's probably something just above that line.

**Comment by richstokes** [comment]
Thanks. Here's the whole file:

```
module.exports = function(environment) {
  let ENV = {
    modulePrefix: 'super-rentals',
    environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }

    // AWS Cognito stuff
    cognito: {
    poolId: 'us-east-2_xxxxxxxxx',
    clientId: '1t89xxxxxxxxxxxxxxxxxq1qs',
    }

  };


  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
    ENV.APP.autoboot = false;
  }

  if (environment === 'production') {
    // here you can enable a production-specific feature
  }

  return ENV;
};
```

**Comment by paulcwatts** [comment]
It looks like you are missing a comma after the `APP` hash, change it to:

```js
    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },  // <-- missing this comma 
```

**Comment by richstokes** [comment]
That did it! Thank you sir.

**Comment by paulcwatts** [comment]
No problem! Let me know if you have any other questions using the addon.
